In [51]:
# Let's install the package we need
!pip install pyDOE3

In [53]:
# Bringing in our tools
from pyDOE3 import bbdesign
import numpy as np
import pandas as pd

## Create a basic Box-Behnken

In [ ]:
# The core syntax is simple
# bbdesign(n, center)

# Where:
# n = how many factors you're working with (minimum 3)
# center = how many center points you want

In [55]:
# Here's a standard 3-factor design
design = bbdesign(3)  # We're specifying 3 factors here
print(design)  # Let's take a peek at what we've got

[[-1. -1.  0.]
 [-1.  1.  0.]
 [ 1. -1.  0.]
 [ 1.  1.  0.]
 [-1.  0. -1.]
 [-1.  0.  1.]
 [ 1.  0. -1.]
 [ 1.  0.  1.]
 [ 0. -1. -1.]
 [ 0. -1.  1.]
 [ 0.  1. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Adjusting center points

In [57]:
# Adding more center points
design_with_more_centers = bbdesign(3, center=5)  # Now with 5 center points
print("With more center points:")
print(design_with_more_centers)  # See the difference?

With more center points:
[[-1. -1.  0.]
 [-1.  1.  0.]
 [ 1. -1.  0.]
 [ 1.  1.  0.]
 [-1.  0. -1.]
 [-1.  0.  1.]
 [ 1.  0. -1.]
 [ 1.  0.  1.]
 [ 0. -1. -1.]
 [ 0. -1.  1.]
 [ 0.  1. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Add factor names

In [59]:
# Creating a design we can use
design = bbdesign(3, center=3)
# Adding meaningful labels
df = pd.DataFrame(design, columns=['Temperature', 'Pressure', 'Concentration'])
print(df)

    Temperature  Pressure  Concentration
0          -1.0      -1.0            0.0
1          -1.0       1.0            0.0
2           1.0      -1.0            0.0
3           1.0       1.0            0.0
4          -1.0       0.0           -1.0
5          -1.0       0.0            1.0
6           1.0       0.0           -1.0
7           1.0       0.0            1.0
8           0.0      -1.0           -1.0
9           0.0      -1.0            1.0
10          0.0       1.0           -1.0
11          0.0       1.0            1.0
12          0.0       0.0            0.0
13          0.0       0.0            0.0
14          0.0       0.0            0.0


## Scale to actual experimental levels

In [ ]:
def scale_design(df, factor_ranges):
    """
    Converts coded design values to real experimental settings

    Parameters:
    -----------
    df : DataFrame
        Your coded design (-1, 0, 1 values)
    factor_ranges : list of tuples
        The min and max for each factor as (min, max)

    Returns:
    --------
    scaled_design : DataFrame
        Your design with actual values to use in the lab
    """
    # Working with a copy to keep the original intact
    scaled_design = df.copy()

    # Processing each factor
    for i, (low, high) in enumerate(factor_ranges):
        # Finding the middle point and the spread
        center = (high + low) / 2
        range_val = high - low

        # Converting: -1 becomes low, 0 becomes center, 1 becomes high
        scaled_design.iloc[:, i] = center + df.iloc[:, i] * range_val / 2

    return scaled_design

In [61]:
# Setting our actual experimental ranges
factor_ranges = [
    (100, 180),   # Temperature from 100°C to 180°C
    (1, 10),      # Pressure from 1 bar to 10 bar
    (0.01, 0.1)   # Concentration from 0.01 to 0.1 %
]

# Creating a design we can use
design = bbdesign(3, center=3)
# Adding meaningful labels
df = pd.DataFrame(design, columns=['Temperature', 'Pressure', 'Concentration'])

# Transforming to real values
scaled_df = scale_design(df, factor_ranges)
print("Ready for the lab:")
print(scaled_df)

Ready for the lab:
    Temperature  Pressure  Concentration
0         100.0       1.0          0.055
1         100.0      10.0          0.055
2         180.0       1.0          0.055
3         180.0      10.0          0.055
4         100.0       5.5          0.010
5         100.0       5.5          0.100
6         180.0       5.5          0.010
7         180.0       5.5          0.100
8         140.0       1.0          0.010
9         140.0       1.0          0.100
10        140.0      10.0          0.010
11        140.0      10.0          0.100
12        140.0       5.5          0.055
13        140.0       5.5          0.055
14        140.0       5.5          0.055


In [63]:
# Export to Excel
scaled_df.to_excel('box_behnken_design_raw.xlsx', index=True)  # Save our design for use in the lab